# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  琪宝宝我爱你
subtitle: 珍惜每分每秒
name: 琪宝宝我爱你
email: 984593084@qq.com
description: 
keywords: 
encoding: "utf-8"
favicon: favicon.ico 

repository: Rambler213/Rambler213.github.io
github_url: https://github.com/Rambler213
url: http://Rambler213.github.io
enforce_ssl: Rambler213.com

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata
  - jekyll-octicons
  
# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. top menu list
menus:

  -
    href: /zsxq.html
    label: 爱的记忆
    target: _self


# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: ityouknow
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: ityouknow
    repo: blog-comments
    oauth:
        client_id: 61bfc53d957e74e78f8f
        client_secret: 31c61e66cdcc9ada8db2267ee779d0bdafac434c
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: ityouknow
    repo: blog-comments
    clientID: 61bfc53d957e74e78f8f
    clientSecret: 31c61e66cdcc9ada8db2267ee779d0bdafac434c
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true
